services:
  - type: web
    name: health-planner-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://bmihealthplanner-backend.onrender.com
